### ISSUE TITLE
Taskwarrior holidays support

### ISSUE THREAD

**Issue by gorrioncillo** [rizel/timewarrior-southamerica-holidays#1]
Sorry to make an issue for this but I already do not know how to make a pull request.
I made a script based on yours which can make a holidays calendar for taskwarrior.
Also I change a little things to make more usable for me (you will notice).
The script needs to pipe the output to a file like `python3 generate_southamerica_holidays.py bolivia 2021 > holidays.es-BO.rc` and copy to somewhere taskwarrior can find it (`/usr/share/doc/task/rc`), maybe add it to README file?

[generate_southamerica_holidays.log](https://github.com/rizel/timewarrior-southamerica-holidays/files/6057799/generate_southamerica_holidays.log) please change the extension to .py, github doesn't let me upload them

**Comment by rizel** [comment]
Hi,
I recently added a clarification in the readme file mentioning the place in the tutorial of timewarrior where it talks about locating your holidays file wherever you want and just adding an import so timewarrior can find it. By the way and if it helps someone, I locate my configuration files between `/opt` and `/home` so when I make OS migrations I know where to look & place my configuration files.
About the piping command... I think that making people think about how it can be used is much way more fun than generating a file. (That's what I thought then and still think now.)
Last but not least, the script I wrote was incomplete and still is. Just made the changes I was foreseeing to complete the missing holidays but haven't finished yet. Any help there will be appreciated :).
